#Application Configuration
server:
  port: 8094
  error:
    include-message: always
    include-binding-errors: always
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Jlpr0893

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"